services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Romanel@2025
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
      - ./Database/create-database.sql:/docker-entrypoint-initdb.d/create-database.sql
    networks:
      - rommanel_net

  backend-core:
    build:
      context: ./Rommanel
      dockerfile: Dockerfile
    container_name: rommanel_api
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=RommanelDB;User=sa;Password=Romanel@2025;
    ports:
      - "5000:80"
    networks:
      - rommanel_net
    entrypoint: ["./wait-for-it.sh", "sqlserver:1433", "--", "dotnet", "Rommanel.dll"]
    volumes:
      - ./wait-for-it.sh:/wait-for-it.sh

  frontend:
    build:
      context: ./RommanelApp
      dockerfile: Dockerfile
    container_name: rommanel_frontend
    ports:
      - "4200:80"
    depends_on:
      - backend-core
    networks:
      - rommanel_net

volumes:
  sqlserver_data:

networks:
  rommanel_net:
